# Generated by Django 3.0.3 on 2021-02-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League_Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
                ('summoner_id', models.CharField(max_length=255)),
                ('tier', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=2)),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('league_points', models.IntegerField()),
            ],
        ),
    ]
