# Generated by Django 3.0.3 on 2021-02-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_league_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league_rank',
            name='rank',
            field=models.CharField(max_length=3),
        ),
    ]
